package com.example.roulette.model.enums;

public enum BetCoinPosition {

    EVEN, ODD, RED, BLACK, FIRST_DOZEN, SECOND_DOZEN, THIRD_DOZEN, FIRST_COLUMN, SECOND_COLUMN, THIRD_COLUMN, ONE_TO_EIGHTEEN, NINETEEN_TO_THIRTY_SIX, ZERO, DOUBLE_ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, ELEVEN, TWELVE, THIRTEEN, FOURTEEN, FIFTEEN, SIXTEEN, SEVENTEEN, EIGHTEEN, NINETEEN, TWENTY, TWENTY_ONE, TWENTY_TWO, TWENTY_THREE, TWENTY_FOUR, TWENTY_FIVE, TWENTY_SIX, TWENTY_SEVEN, TWENTY_EIGHT, TWENTY_NINE, THIRTY, THIRTY_ONE, THIRTY_TWO, THIRTY_THREE, THIRTY_FOUR, THIRTY_FIVE, THIRTY_SIX;

}
